### ISSUE TITLE
String contains number break the rest of the syntax color

### ISSUE THREAD

**Issue by kotakerdus** [Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code#1]
Hi, whenever I tried to put a number into "" right after the quotation mark it break the rest of the syntax color but not when there is space before the number

![image](https://user-images.githubusercontent.com/33751190/38194464-02cfdb6c-36bb-11e8-9013-49ba45db49b0.png)

**Comment by SteamUpdate** [comment]
@Maximetinu can you update a [csharp.tmLanguage.json](https://github.com/Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code/blob/development/theme-sublime-monokai-csharp-colorizer/syntaxes/csharp.tmLanguage.json) file, please?

**Comment by maximetinu** [comment]
This has been fixed in the new 1.0.0 update! You can download it now [from the VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=maximetinu.identical-sublime-monokai-csharp-theme-colorizer). It now supports C, C++ and Python too :)
