### ISSUE TITLE
Multiplying variables inside parentheses changes the variable color

### ISSUE THREAD

**Issue by Cellorator** [Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code#12]
Multiplying variables inside parentheses messes up text colors in C#, like so:
![image](https://user-images.githubusercontent.com/66387348/88941198-57c48380-d24e-11ea-9688-7a20794f8a47.png)

instead of:
![image](https://user-images.githubusercontent.com/66387348/88941331-83e00480-d24e-11ea-9d16-f2847246801e.png)

**Comment by maximetinu** [comment]
Thanks for reporting it!

Currently, I am no longer fixing bugs due to a lack of time, but it will help when I'll get to work on it.

**Comment by maximetinu** [comment]
This has been fixed in the new 1.0.0 update! You can download it now [from the VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=maximetinu.identical-sublime-monokai-csharp-theme-colorizer). It now supports C, C++ and Python too :)
