### ISSUE TITLE
Double quote followed by an underscore

### ISSUE THREAD

**Issue by Devwulf** [Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code#14]
Hello! It seems this plugin causes syntax highlighting errors for the lines following an instance of a double quote followed by an underscore, like a string `"_something"`. Here is a visual example of the issue:

![commented](https://user-images.githubusercontent.com/58543895/114238522-bfd97680-9952-11eb-9b02-d71fd90e6c18.png)

![uncommented](https://user-images.githubusercontent.com/58543895/114238530-c36cfd80-9952-11eb-8bd4-17e597a4e33b.png)

When the offending line is commented out, the syntax highlighting works as expected. But when uncommented, the syntax highlighting gets ruined. In this case, the string starts with two underscores, but this also happens with only one underscore.

**Comment by maximetinu** [comment]
Thanks for reporting it 👍 I'm not doing any support or maintenance to the project currently though, but I'd like to come back to it sometime soon and these bug reports will be very handy 🙂

**Comment by maximetinu** [comment]
This is fixed in the new 1.0.0 update! You can download it now [from the VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=maximetinu.identical-sublime-monokai-csharp-theme-colorizer). It now supports C, C++ and Python too :)
