### ISSUE TITLE
Maybe better icon in the market?

### ISSUE THREAD

**Issue by MuggleWang** [Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code#18]
It's a great theme, but the icon in the market is too rudimentary. Do you consider replacing it with a better-looking icon?

For example, the icon on the monokai.pro?
![Monokai-logo](https://user-images.githubusercontent.com/22472622/145702582-5a9759fd-aa4d-4fac-8004-4fb952d63fe6.png)

**Comment by MuggleWang** [comment]
![Monokai-sublime-logo](https://user-images.githubusercontent.com/22472622/145702808-e49e00fc-dc4e-4601-b199-748153df76f0.png)
![Monokai-vscode-logo](https://user-images.githubusercontent.com/22472622/145702813-09b313d4-dbd5-460b-a66e-ea858ed4542c.png)

**Comment by maximetinu** [comment]
Hi @MuggleWang. I know the icon is rudimentary, but I lack the skills to design a better one as I'm not a graphic designer 😕. We can't of course use the same of Monokai.pro because of copyright, but I'd be happy to accept a contribution to replace the icon with a better one 🙂

**Comment by maximetinu** [comment]
Done at v1.2.2 ! 😄
