### ISSUE TITLE
Update 0.11.0 does not install

### ISSUE THREAD

**Issue by egabrum** [Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code#3]
Update 0.11.0 is not installing for me. The green button goes blue with  "Installing..." for a second and them back to green with "Update to 0.11.0"

**Comment by kellpossible** [comment]
same problem here

**Comment by kuwantum** [comment]
Adding another voice to this

**Comment by maximetinu** [comment]
Thanks for reporting it!

I should be fixed now in update 0.11.1 with a minor patch in package.json, try update again.

**Comment by kuwantum** [comment]
@Maximetinu Confirmed now working, thanks for the quick fix 🙏
