### ISSUE TITLE
Variable with underscore prefix being colorized only sometimes.

### ISSUE THREAD

**Issue by j-schoch** [Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code#7]
See the two attached screenshots. The variable "_instance" has the underscore in white inside the "if()" statement, but colorized purple elsewhere.

![screen shot 2019-01-30 at 3 21 48 pm](https://user-images.githubusercontent.com/5287619/52010241-08f42d00-24a3-11e9-9130-e5e0bae43172.png)
![screen shot 2019-01-30 at 3 22 17 pm](https://user-images.githubusercontent.com/5287619/52010242-08f42d00-24a3-11e9-9e83-f530419e4f56.png)

**Comment by maximetinu** [comment]
Thank u very much for the bug reports!

I have some things to fix before this extension could be considered as an actual Identical Sublime Text theme, but atm I really don't have any time to work on it :(

I hope to find time to fix these things soon. Until then, thank u for the issue!

**Comment by maximetinu** [comment]
This has been fixed in the new 1.0.0 update! You can download it now [from the VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=maximetinu.identical-sublime-monokai-csharp-theme-colorizer). It now supports C, C++ and Python too :)
