### ISSUE TITLE
Attributes should be colored in the class definition color

### ISSUE THREAD

**Issue by j-schoch** [Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code#8]
See attached screenshot.  Attributes are currently colored as a variable name or plain text (white), but in sublime they are colored as a class name (sublime blue).
![screen shot 2019-01-30 at 3 27 17 pm](https://user-images.githubusercontent.com/5287619/52010536-c54df300-24a3-11e9-8513-9ebdf2249c84.png)

**Comment by maximetinu** [comment]
This has been fixed in the new 1.0.0 update! You can download it now [from the VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=maximetinu.identical-sublime-monokai-csharp-theme-colorizer). It now supports C, C++ and Python too :)
