### ISSUE TITLE
string's start with a digit are colorized incorrectly

### ISSUE THREAD

**Issue by majidmadadi** [Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code#9]
the string ` "0some text"` is colored as https://imgur.com/DC0MQ8H

**Comment by bluemorgan23** [comment]
I've been dealing with this issue as well. I've been working around it by preceding strings with $ or @ until I ultimately uninstalled the extension. I'm glad that this bug has been noted because I really do enjoy the theme.

**Comment by Scooterzt** [comment]
Same here. "\0" usually help, but stupid.

**Comment by bluemorgan23** [comment]
I want to add that not only would the string’s syntactical highlighting be incorrect, but it would throw off the entire file as well.

**Comment by maximetinu** [comment]
This has been fixed in the new 1.0.0 update! You can download it now [from the VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=maximetinu.identical-sublime-monokai-csharp-theme-colorizer). It now supports C, C++ and Python too :)
